### ISSUE TITLE
npm run test fails

### ISSUE THREAD

**Issue by HansS** [dsebastien/modernWebDevBuild#51]
[18:58:03] Requiring external module babel-core/register
module.js:340
    throw err;
    ^

Error: Cannot find module 'phpfn'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Hans\Web\js\es6\es6-module-loader\solitaire-me-ts\node_modules\gulp-cssimport\helper.js:9:13)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Hans\Web\js\es6\es6-module-loader\solitaire-me-ts\node_modules\babel-register\lib\node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Hans\Web\js\es6\es6-module-loader\solitaire-me-ts\node_modules\gulp-cssimport\gulp-cssimport.js:8:15)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Hans\Web\js\es6\es6-module-loader\solitaire-me-ts\node_modules\babel-register\lib\node.js:138:7)
 'Please commit all changes generated by building'; exit 1

**Comment by dsebastien** [comment]
I haven't implemented testing support yet, the current script doesn't do anything useful.
See #14 & #47
